name: Github Actions Demo
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "${{github}}"
      - name: "komut"
        run: "echo ${{github}}"